steps:
  # Step 1: Build Docker image (Toronto)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${COMMIT_SHA}'  # Toronto
      - '.' 

  # Step 2: Push to Artifact Registry (Toronto)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${COMMIT_SHA}'

  # Step 3: Deploy to Cloud Run (Toronto)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy assignment2-service \
          --image=northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${COMMIT_SHA} \
          --region=northamerica-northeast2 \
          --platform=managed \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: 'gs://nacer-logs'
