steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'
      - '.' 

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'assignment2-service'
      - '--image'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'
      - '--region'
      - 'northamerica-northeast2'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'PORT=8080'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
