steps:
  # Docker Build (Toronto region)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'
      - '.'  # Assumes Dockerfile is in root directory

  # Docker Push (Toronto region)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'

  # Cloud Run Deploy (Toronto region)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'assignment2-service'  # Match your service name
      - '--image'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'
      - '--region'
      - 'northamerica-northeast2'  # Toronto region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Optional for public access

images:
  - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
