steps:
  # Step 1: Build Docker image (Iowa region)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${COMMIT_SHA}'  # Iowa
      - '.' 

  # Step 2: Push to Artifact Registry (Iowa)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${COMMIT_SHA}'

  # Step 3: Deploy to Cloud Run (Iowa)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy assignment2-service \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/nacer-100961510/app:${COMMIT_SHA} \
          --region=us-central1 \  # Iowa
          --platform=managed \
          --quiet

options:
  logging: NONE  # Bucket must be in `us-central1`
